(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2631686) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:2631686) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 400
    at settle (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:1909:12)
    at IncomingMessage.handleStreamEnd (/home/addrqioi/nodevenv/app3/14/lib/node_modules/axios/dist/node/axios.cjs:2989:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:2631686) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)
